alias n=nvim
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH=$PATH:/usr/local/go/bin

# Kubectl
alias kubectl=kubecolor
alias k=kubecolor
source <(kubecolor completion zsh)

# editor
export EDITOR="nvim"

# git
git config --global alias.ac '!f() { git add . && git commit -m "$1"; }; f'
